### ISSUE TITLE
IE8 and IE9 support

### ISSUE THREAD

**Issue by rajasri215** [timdown/rangyinputs#10]
I tried to set the focus to an input element and used insertText ( with behavior as carettoend) to add a character the same text field. As per the document, I assume that the cursor position will be updated and it was visible though. For next insert, I tried to fetch the caret position (updated) using getSelection after setting focus() and proceed with next insertion. Every time it returns 0 and the insertion happens at 0th position only.

**Comment by timdown** [comment]
This is almost certainly because you're doing this in a `click` (or similar) handler on a buttton that has stolen focus from your textarea or input and destroyed the selection by the time the `click` event fires. You can work around this by using `mousedown` instead, or by making the button unselectable.

**Comment by rajasri215** [comment]
Thanks a lot Tim. What you have mentioned above is what is happening in my case. Thanks for your time.
